adding compatibility to Spark 3
mspnp/spark-monitoring pull request #115
Opened 2020-11-03 10:17 UTC by dfanesiDB

### Changes proposed in this PR
I have added the support for spark 3 using the same codebase and same tests for both versions of spark and scala. 

### Code changes:
StreamingListenerHandlers.scala:
It looks like a method was renamed in the new release of spark, so I am taking away the optional "override" keyword and adding the new method as well. 

### Changes to unit tests
The new version of the io.dropwizard.metrics:metrics-core has moved the CpuTimeClock class. The only way to support both versions with the same tests is to instantiate the object using reflections. 

Spark 3 has also added some new parameters to the constructors of events. I decided to use the same approach to not duplicate code: I am instantiating the objects of those classes using reflections.

Reflections add a lot of complexity to the unit tests, but it enables us to reuse the same unit tests and to not duplicate code. The alternative would be to duplicate code for the unit tests, but then we would have to maintain two unit test suites, which is not ideal as well. Unfortunately, none of the choices are good in my opinion.

2020-11-05 11:03 UTC, Nemeczek commented
I hope this will get merged soon :)

2020-11-05 21:50 UTC, hallihan commented
@dfanesiDB - are you able to review/sign the CLA linked above?

2020-11-06 09:38 UTC, dfanesiDB commented
Hi @hallihan, unfortunately, I am still waiting the approval of my legal team. I will ping them again today to see if they are ok with me signing this. I guess you can start the review in the meantime if you want to.

2020-11-12 13:34 UTC, hallihan commented
@dfanesiDB any update on the CLA?  I'm not able to start a review until this is signed.

2020-11-16 21:53 UTC, dfanesiDB commented
@hallihan sorry for the delay. I was finally able to get the approval I needed.

2020-11-17 13:08 UTC, hallihan commented
> @hallihan sorry for the delay. I was finally able to get the approval I needed.

Great!  I should be able to look at this over the next couple of days.

2020-11-17 16:51 UTC, hallihan requested changes
A few small suggestions to align profiles between the main project and the sample job pom.xml.  I already ran the updated code against Azure Databricks 5.5, 6.6, 7.2, and 7.4 without any issues.  Thanks a ton for this contribution!

2020-11-17 16:51 UTC, hallihan commented on README.md
> +| `7.3` | `scala-2.12_spark-3.0.1` |
```suggestion
| `7.3` - `7.4` | `scala-2.12_spark-3.0.1` |
```

2020-11-17 16:51 UTC, hallihan commented on src/pom.xml
> +            <activation>
Only one profile should be marked `activeByDefault`, can you remove it from `scala-2.11_spark-2.4.5` and `scala-2.12_spark-3.0.0`?

2020-11-17 16:51 UTC, hallihan commented on src/pom.xml
> +        <profile>
Adding comment here since GitHub won't let me comment on files that are outside of the diff.  Can you add profiles for `scala-2.12_spark-3.0.0` and `scala-2.12_spark-3.0.1` in `sample/spark-sample-job/pom.xml`?  We tell the user in the readme to use these same profiles when building the sample and if the profile is missing they will get a warning like:
> [WARNING] The requested profile "scala-2.12_spark-3.0.1" could not be activated because it does not exist.
and the build will proceed with the `activeByDefault` profile.

See the diff below for the changes I made when testing:
```
diff --git a/sample/spark-sample-job/pom.xml b/sample/spark-sample-job/pom.xml
index adfea2e..ee71f7c 100644
--- a/sample/spark-sample-job/pom.xml
+++ b/sample/spark-sample-job/pom.xml
@@ -21,9 +21,6 @@
         </profile>
         <profile>
             <id>scala-2.11_spark-2.4.5</id>
-            <activation>
-                <activeByDefault>true</activeByDefault>
-            </activation>
             <properties>
                 <jetty.version>9.4.31.v20200723</jetty.version>
                 <slf4j.version>1.7.16</slf4j.version>
@@ -32,6 +29,29 @@
                 <scala.compat.version>2.11</scala.compat.version>
             </properties>
         </profile>
+        <profile>
+            <id>scala-2.12_spark-3.0.0</id>
+            <properties>
+                <jetty.version>9.4.31.v20200723</jetty.version>
+                <slf4j.version>1.7.16</slf4j.version>
+                <spark.version>3.0.0</spark.version>
+                <scala.version>2.12.12</scala.version>
+                <scala.compat.version>2.12</scala.compat.version>
+            </properties>
+        </profile>
+        <profile>
+            <id>scala-2.12_spark-3.0.1</id>
+            <activation>
+                <activeByDefault>true</activeByDefault>
+            </activation>
+            <properties>
+                <jetty.version>9.4.31.v20200723</jetty.version>
+                <slf4j.version>1.7.16</slf4j.version>
+                <spark.version>3.0.1</spark.version>
+                <scala.version>2.12.12</scala.version>
+                <scala.compat.version>2.12</scala.compat.version>
+            </properties>
+        </profile>
     </profiles>

     <properties>
```

2020-11-18 18:21 UTC, dfanesiDB commented on src/pom.xml
> +        <profile>
@hallihan thank you for reviewing my changes. I applied all your suggestions.

2020-11-18 18:40 UTC, hallihan approved these changes

2020-11-18 18:41 UTC, merged