Add filtering capability to Spark Monitoring library
mspnp/spark-monitoring pull request #118
Opened 2020-12-04 21:53 UTC by hallihan

Implement a basic regex filter for each of SparkLoggingEvent_CL, SparkMetric_CL, and SparkListenerEvent_CL.
Provide documentation and examples of how to edit the launcher script to populate the necessary environment variables.
Include documentation on how to use built-in log4j threshold based filter.

Fixes: #95

2020-12-04 23:02 UTC, ckittel requested changes
Hey there.  I'm NOT the Spark expert you were looking for, but I did do a review of the code as I read it, and the documentation.  Findings below.  Generally speaking, I think it looks good and seems to fit well in each spot you implemented it.  Again, not an expert at all on runtime usage/customer expectations/etc of this :)  So take this review for what it's worth.  Minimal :P

2020-12-14 18:49 UTC, hallihan commented on src/spark-listeners/scripts/spark-monitoring.sh
> +# is in the event name.
I flipped this suggestion around and updated the example to match the comment since that was the original intent.

2020-12-14 18:49 UTC, hallihan commented on src/spark-listeners-loganalytics/src/test/java/com/microsoft/pnp/logging/loganalytics/LogAnalyticsAppenderTest.java
> +        nameregex.set(null,"12.*34");
Added test cases

2020-12-14 18:50 UTC, hallihan commented on src/spark-listeners-loganalytics/src/test/java/com/microsoft/pnp/logging/loganalytics/LogAnalyticsAppenderTest.java
> +        assertEquals(sut.getFilter().decide(test),Filter.DENY);
Good catch, I changed the message text to not include the phrase "password" in the fake password.

2020-12-14 18:50 UTC, hallihan commented on src/spark-listeners-loganalytics/src/test/java/com/microsoft/pnp/logging/loganalytics/LogAnalyticsAppenderTest.java
> +        when(test.getLoggerName()).thenReturn("12_This_is_a_test_34");
Added a test case

2020-12-15 01:38 UTC, ckittel approved these changes
🦜

2021-01-10 22:33 UTC, jocontr reviewed
Looks good; just the minor typos. I like the idea of the regex pattern to limit volume.

2021-01-10 22:33 UTC, jocontr commented on docs/filtering.md
> +You can uncomment and edit the `LA_SPARKLISTENEREVENT_REGEX` environment variable that included included in [spark-monitoring.sh](../src/spark-listeners/scripts/spark-monitoring.sh) to limit the logg
typo

2021-01-10 22:33 UTC, jocontr commented on docs/filtering.md
> +You can uncomment and edit the `LA_SPARKLOGGINGEVENT_NAME_REGEX` environment variable that included included in [spark-monitoring.sh](../src/spark-listeners/scripts/spark-monitoring.sh) to limit the
typo

2021-01-11 13:28 UTC, hallihan commented on docs/filtering.md
> +You can uncomment and edit the `LA_SPARKLISTENEREVENT_REGEX` environment variable that included included in [spark-monitoring.sh](../src/spark-listeners/scripts/spark-monitoring.sh) to limit the logg
Fixed, good catch!

2021-01-11 13:28 UTC, hallihan commented on docs/filtering.md
> +You can uncomment and edit the `LA_SPARKLOGGINGEVENT_NAME_REGEX` environment variable that included included in [spark-monitoring.sh](../src/spark-listeners/scripts/spark-monitoring.sh) to limit the
Fixed

2021-01-11 13:35 UTC, merged